version: "3.8"

services:
  # SERVICE DASH
  dash:
    build: ./data-dash
    ports:
      - "8050:8050"

  # SERVICE FASTAPI 
  fastapi:
    build: 
      context: ./data-fastapi
      dockerfile : Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./data-fastapi:/app           # Monte le répertoire de travail dans le conteneur
    ports:
      - "8000:8000"      
    restart: on-failure


  # SERVICE STREAMLIT 
  streamlit:
    build: ./data-streamlit
    ports:
      - "8501:8501"

  # SERVICE REACT    
  react:
    build: 
      context: ./dev-react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dev-react:/app              # Monte le répertoire de travail local dans le conteneur
      - /app/node_modules             # Préserve les node_modules du conteneur
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: npm run dev